- name: Copy files to host
  become: True
  copy:
    src: manifests
    dest: $PWD/monitoring/

- name: Template files to host
  template:
    src: "{{ item }}"
    dest: $PWD/monitoring/manifests/{{ item | basename | regex_replace('\.j2$', '') }}
  with_fileglob:
    - "manifests/*.yaml.j2"

- name: Install Monitoring setup
  become_user: "{{ user }}"
  command: "{{ item }}"
  with_items:
    - kubectl apply --server-side -f monitoring/manifests/setup

- pause: seconds=20
- name: Install Monitoring components
  become_user: "{{ user }}"
  command: "{{ item }}"
  with_items:
    - kubectl apply -f monitoring/manifests/
