---
- name: Read the /etc/kubeedge/config/edgecore.yaml
  become: True
  slurp:
    path: /etc/kubeedge/config/edgecore.yaml
  register: r_myfile

- name: extract the data
  set_fact:
    mydata: "{{ r_myfile['content'] | b64decode | from_yaml }}"

- name: Modify edgeStream to true
  set_fact:
    mydata: "{{ mydata | combine({'modules': {'edgeStream': {'enable': true}}}, recursive=True) }}"

- name: Modify edged clusterDNS
  set_fact:
    mydata: "{{ mydata | combine({'modules': {'edged': {'clusterDNS': '10.96.0.10'}}}, recursive=True) }}"

- name: Modify edged clusterDomain
  set_fact:
    mydata: "{{ mydata | combine({'modules': {'edged': {'clusterDomain': 'cluster.local'}}}, recursive=True) }}"

- name: Modify metaManager,  metaServer enable
  set_fact:
    mydata: "{{ mydata | combine({'modules': {'metaManager': {'metaServer': {'enable': true}}}}, recursive=True) }}"

- debug:
    msg: "{{ mydata }}"

- name: Write back to /etc/kubeedge/config/edgecore.yaml
  become: True
  copy:
    content: "{{ mydata | to_nice_yaml }}"
    dest: /etc/kubeedge/config/edgecore.yaml

- name: disable proxy checking
  become: True
  ini_file: dest=/etc/kubeedge/edgecore.service section=Service option=Environment value='"CHECK_EDGECORE_ENVIRONMENT=false"' backup=yes
  tags: configuration

- name: Kill edgecore and restart it
  become: True
  command: systemctl restart edgecore.service
