openstack_user_name        = ""
openstack_tenant_name      = ""
openstack_password         = ""
openstack_auth_url         = "https://cc.lrz.de:5000/v3"
openstack_project_name     = ""
openstack_project_id       = ""
openstack_user_domain_name = "ADS"
openstack_region           = "RegionOne"
