- name: Install the helm on amd64
  command: "{{ item }}"
  become: True
  with_items:
    - wget https://get.helm.sh/helm-v3.8.0-rc.1-linux-amd64.tar.gz
    - tar -zxvf helm-v3.8.0-rc.1-linux-amd64.tar.gz
    - mv linux-amd64/helm /usr/local/bin/helm