---
# file: kube_edge_cloud.yml
- hosts: master
  become: True
  vars:
    keadm_version: 1.9.1
    keadm_host_os: linux-amd64
  roles:
    - role: keadm
    - role: keadm-cloud
    - role: keadm-cloud-logs
    - role: keadm-cloud-edgemesh
