---
# file: kube_edge_edge.yml
- hosts: edge
  become: True
  roles:
    - role: common
    - role: docker-edge
    - role: keadm
    - role: keadm-edge
    - role: keadm-edge-logs
    - role: keadm-edge-edgemesh
