---
# file: sedna.yml
- hosts: master
  become: True
  roles:
    - role: sedna-cloud
      vars:
        user: ubuntu
        nvidia: "no"
        proxy: "no"
        kubernetes_version: 1.22.0-00
        keadm_version: 1.9.1
        keadm_host_os: linux-amd64
