- name: Install arkade tool
  become: True
  command: "{{ item }}"
  with_items:
    - wget https://github.com/alexellis/arkade/releases/latest/download/arkade
    - chmod +x arkade
    - mv arkade /usr/local/bin/arkade

- name: Install Openfaas
  become: True
  command: "{{ item }}"
  with_items:
    - arkade install openfaas --set openfaasPRO=False
